stages:
  - stage:
      - job:
          resourceType: REMOTE
          pool:
            type: DockerOnDevCloud
            container: mirrors.tencent.com/ci/tlinux_ci:0.2.0.4
            env:
              jdk: 1.8.0_161
          steps:
            - taskType: 'syncLocalCode@latest'
              displayName: 同步代码到云端
              inputs:
                syncGitRepository: true #同步Git的提交日期、处理人等信息
            - taskType: marketBuild@latest
              displayName: 腾讯代码分析(最新)
              inputs:
                atomCode: CodeccCheckAtomDebug
                version: 4.*
                data:
                  input:
                    beAutoLang: true
                    # languages: # 工程语言, 必选, 可取值："C_CPP", "JAVA", "C_SHARP", "JS", "OC", "PYTHON", "PHP", "RUBY", "GOLANG", "SWIFT", "TYPESCRIPT", "KOTLIN", "LUA", "OTHERS"
                    #   - "JAVA"
                    checkerSetType: "openScan" #openScan对应按开源治理要求配置规则集，epcScan对应按PCG EPC要求配置。选了openScan或epcScan则不需要填写后面的内容
                    toolScanType: "0" # 扫描方式。0是全量扫描，1是增量扫描