{{- if .Values.init.entrance.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-init-entrance
  labels: {{- include "codecc.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: init-entrance
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels: {{- include "codecc.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: init-entrance
    spec:
      containers:
        - name: init-entrance
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.init.entrance.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.init.entrance.image.pullPolicy }}
          command: ['/bin/sh','-c','/data/workspace/init-entrance.sh']
          env:
            - name: CODECC_USERNAME
              value: {{ include "codecc.mongodb.username" . }}
            - name: CODECC_PASSWORD
              value: {{ include "codecc.mongodb.password" . }}
            - name: CODECC_HOST
              value: {{ include "codecc.mongodb.fullname" . }}
            - name: CODECC_PORT
              value: {{ include "codecc.mongodb.port" . | quote }}
            - name: CODECC_AUTH_DB_DEFECT
              value: {{ include "codecc.mongodb.defectAuthDB" . }}
            - name: CODECC_AUTH_DB_TASK
              value: {{ include "codecc.mongodb.taskAuthDB" . }}
            - name: CODECC_AUTH_DB_QUARTZ
              value: {{ include "codecc.mongodb.quartzAuthDB" . }}
            - name: CODECC_IPV6_ENABLE
              value: {{ .Values.ipv6.enabled | quote }}
      restartPolicy: OnFailure
{{- end }}
