apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bkci-codecc-quartz
  name: bkci-codecc-quartz
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bkci-codecc-quartz
  template:
    metadata:
      labels:
        app: bkci-codecc-quartz
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
        - ip: "{{ .Values.host.BK_CI_PRIVATE_IP }}"
          hostnames:
            - "{{ .Values.env.BK_CI_PRIVATE_HOST }}"
      containers:
        - image: {{ .Values.image.hub }}/bkci-codecc-quartz:{{ .Values.image.tag }}
          name: bkci-codecc-quartz
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /data/docker/bkci/codecc/backend/
          command: ['/bin/sh','-c','/data/docker/bkci/codecc/backend/module_run_codecc.sh']
          env:
            - name: CONSUL_SERVER
              value: {{ .Values.consul.server }}
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP