replicaCount: 1

image:
  hub: docker.io
  tag: "1.0"
  pullPolicy: Always

volume:
  nfs:
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Retain
  storage: 10Gi

host:
  BK_CI_PRIVATE_IP: 127.0.0.1 #BK_CI_PRIVATE_HOST对应的IP

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root

mongodb:
  host: 127.0.0.1
  port: 27017
  user: root
  password:

consul:
  server: consul-server.bk #consul server的host或者IP
  datacenter: dc1

env:
  BK_CODECC_DATA_DIR:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_CODECC_HOME: /data/docker/bkci/codecc   # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_CODECC_PRIVATE_URL:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_DOMAIN: devops.bk.tencent.com   # 无默认值. 按需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境需修改, 建议使用用户持有的公网域名(解析为内网IP亦可).
  BK_HOME: /data/docker/bkci   # 无默认值. 按需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境需修改, /data/bkee (企业版默认)或 /data/bkce (社区版默认).
  BK_HTTP_SCHEMA:    # 无默认值. 按需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境需修改, http 或 https.
  BK_IAM_PRIVATE_URL:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_LICENSE_PRIVATE_URL:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_PAAS_FQDN:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_PAAS_HTTPS_PORT:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_PAAS_PRIVATE_URL:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_PAAS_PUBLIC_URL:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_REPO_HOST:    # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_SSM_HOST:   # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  BK_SSM_PORT:   # 无默认值. 无需修改. 声明依赖, 蓝鲸环境下会自动填充. 其他环境无需填写.
  ##########
  #基础配置
  ##########
  BK_CI_APP_CODE: bk_ci   # 默认bk_ci. 请勿修改. 本系统在蓝鲸体系中的唯一ID.
  BK_CI_APP_TOKEN:    # 无默认值. 无需修改. 蓝鲸环境中自动生成. 其他环境填写无意义. 用于ESB认证.
  BK_CI_AUTH_PROVIDER: sample   # 默认bk_login_v3. 按需修改. 认证服务. "sample"为无认证, "bk_login"为蓝鲸认证, "bk_login_v3"为蓝鲸IAMv3认证.
  BK_CI_BADGE_URL:    # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_DATA_DIR: $BK_HOME/public/ci   # 默认$BK_HOME/public/ci. 无需修改. CI的数据存储目录.
  BK_CI_DOCS_URL:    # 默认https://bk.tencent.com/docs. 按需修改. 帮助文档主页. 如无企业内文档站点, 请保持默认.
  BK_CI_ENV: codecc-prod   # 默认prod. 废弃. 待清理配置文件及相关代码.
  BK_CI_FQDN:    # 默认devops.$BK_DOMAIN. 按需修改. 完全合格域名(即公网域名, 可解析为内网IP), 用于在CI集群外访问CI.
  BK_CI_GATEWAY_CORS_ALLOW_LIST:    # 无默认值. 按需修改. 网关允许cors的来源域名, 一般无需填写.
  BK_CI_GATEWAY_DNS_ADDR: kube-dns.kube-system.svc.cluster.local  # 默认127.0.0.1:8600. 无需修改. 网关内部使用的DNS, 一般指向本机consul.
  BK_CI_GATEWAY_REGION_NAME:    # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_GATEWAY_SSM_TOKEN_URL: /api/v1/auth/access-tokens   # 默认/api/v1/auth/access-tokens. 无需修改. 用户认证token验证地址. bk_login_v3使用ssm. bk_login使用iam. 二者入口不同.
  BK_CI_HOME: /data/docker/bkci/ci   # 默认$BK_HOME/ci. 无需修改. CI的安装目录.
  BK_CI_HOST: bk-ci.serice.consul   # 默认bk-ci.serice.consul. 无需修改. CI在蓝鲸集群内的主机名.
  BK_CI_HTTP_PORT: 80   # 默认80. 无需修改. 集群一般使用http端口互联.
  BK_CI_HTTPS_PORT: 443   # 默认443. 无需修改. BK_HTTP_SCHEMA 为https时有效.
  BK_CI_IAM_CALLBACK_USER: bk_iam   # 默认bk_iam. 请勿修改. 供iam系统发起回调时使用的用户名.
  BK_CI_IAM_ENV: prod   # 默认prod. 废弃. 待清理配置文件及相关代码.
  BK_CI_JOB_FQDN:    # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_JWT_RSA_PRIVATE_KEY:    # 无默认值. 按需修改. JWT RSA密钥对. 单行, 需要确保最终渲染为\n. 建议使用附带的脚本生成.
  BK_CI_JWT_RSA_PUBLIC_KEY:    # 无默认值. 按需修改.
  BK_CI_LOGS_DIR: /data/docker/bkci/logs/ci   # 默认$BK_HOME/logs/ci. 无需修改. CI日志主目录, 各proj会自动创建子目录.
  BK_CI_PAASCI_FQDN:    # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_PRIVATE_HOST: devops.bk.tencent.com   # 默认bk-ci.service.consul. 无需修改. 蓝鲸集群内使用的主机名.
  BK_CI_PRIVATE_URL: http://bk-ci.service.consul   # 默认http://bk-ci.service.consul. 无需修改. 蓝鲸集群内使用的url, 如iam回调ci时.
  BK_CI_PUBLIC_URL: http://devops.bk.tencent.com   # 默认$BK_HTTP_SCHEMA://devops.$BK_DOMAIN. 按需修改. 蓝盾为集群外访问提供的URL. 如修改过端口, 请更新这里.

  ##########
  #公共依赖
  ##########
  BK_CI_CONSUL_DEVNET_GRAY_IP:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_CONSUL_DISCOVERY_TAG: ci   # 默认devops. 无需修改. 服务发现时的标签, 兼作服务名命名空间(后缀).
  BK_CI_CONSUL_DISCOVERY_TAG_DEVNET: codecc   # 默认devops. 无需修改. 服务发现时的标签, 兼作服务名命名空间(后缀).
  BK_CI_CONSUL_IP: consul.local
  BK_CI_CONSUL_DNS_PORT: 53   # 默认53. 无需修改. consul agent的dns port
  BK_CI_CONSUL_DOMAIN: ci   # 默认consul. 请勿修改. consul私有域名
  BK_CI_CONSUL_DEVNET_IP: consul.local
  BK_CI_CONSUL_DNS_PORT_DEVNET: 53   # 默认53. 无需修改. consul agent的dns port
  BK_CI_CONSUL_DOMAIN_DEVNET: consul   # 默认consul. 请勿修改. consul私有域名
  BK_CI_CONSUL_GRAY_IP:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_CONSUL_HTTP_PORT: 8500   # 默认8500. 按需修改. consul agent的http port
  BK_CI_CONSUL_PORT: 8500   # 默认8500. 废弃. 待清理配置文件及相关代码.
  BK_CI_CONSUL_PORT_DEVNET: 8500   # 默认8500. 废弃. 待清理配置文件及相关代码.
  BK_CI_MYSQL_ADDR: 127.0.0.1:3306   # 默认mysql-ci.service.consul:3306. 按需修改. CI专用的MySQL数据库地址, HOST:PORT形式.
  BK_CI_MYSQL_PASSWORD: root   # 无默认值. 按需修改.
  BK_CI_MYSQL_USER: root   # 默认bk_ci. 按需修改.
  BK_CI_PAAS_LOGIN_URL: /login/?c_url=  # 默认$BK_PAAS_PUBLIC_URL/login/?c_url:. 无需修改. 对接蓝鲸登录时, 蓝鲸登录主页. CI会在结尾直接追加回调地址.
  BK_CI_RABBITMQ_ADDR: rabbitmq:5672   # 默认rabbitmq-ci.service.consul:5672. 按需修改. CI专用的RabbitMQ地址, HOST:PORT形式.
  BK_CI_RABBITMQ_PASSWORD: test  # 无默认值. 按需修改.
  BK_CI_RABBITMQ_USER: test   # 默认bk_ci. 按需修改.
  BK_CI_RABBITMQ_VHOST: mq   # 默认bk_ci. 按需修改. 建议使用独立的vhost.
  BK_CI_REDIS_DB: 7   # 无默认值. 按需修改. 选择使用的db.
  BK_CI_REDIS_HOST: 127.0.0.1   # 默认redis-ci.service.consul. 按需修改. CI专用的Redis地址.
  BK_CI_REDIS_PASSWORD:   # 无默认值. 按需修改.
  BK_CI_REDIS_PORT: 6379   # 默认6379. 按需修改.
  BK_CI_REDIS_SENTINEL_ADDR:   # 无默认值. 无需修改. CI专用的Redis集群地址. 目前暂无法使用集群协议接入.
  BK_CI_REDIS_SENTINEL_MASTER_NAME:   # 无默认值. 无需修改
  BK_CI_CONSUL_DISCOVERY_SUFFIX_DEVNET: ci

  ##########
  #微服务配置
  ##########
  BK_CI_CODEOA_API_KEY:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_CODEOA_API_URL:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_CODEOA_GIT_URL:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_ENVIRONMENT_AGENT_COLLECTOR_ON: false   # 默认false. 按需修改. 第三方构建机状态上报, 如开启, 则需要influxdb.
  BK_CI_PROCESS_EVENT_CONCURRENT: 20   # 默认20. 无需修改. process并发保护.
  BK_CI_REPOSITORY_GITHUB_APP:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_GITHUB_CLIENT_ID:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_GITHUB_CLIENT_SECRET:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_GITHUB_SIGN_SECRET:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_GITLAB_URL:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_GIT_PLUGIN_GROUP_NAME:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_GIT_PRIVATE_TOKEN:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_GIT_URL:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_SVN_API_KEY:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_SVN_API_URL:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_REPOSITORY_SVN_WEBHOOK_URL:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_STORE_USER_AVATARS_URL: $BK_PAAS_PUBLIC_URL/console/static/img/getheadimg.jpg?   # 默认$BK_PAAS_PUBLIC_URL/console/static/img/getheadimg.jpg?. 无需修改. PaaS用户头像, 目前仅显示默认头像.

  ##########
  #微服务依赖
  ##########
  BK_CI_DOCKER_IMAGE_PREFIX:   # 无默认值. 按需修改. Docker镜像前缀. 当填写的镜像标识不含主机名信息, 则尝试使用此前缀.
  BK_CI_DOCKER_PORT: 8090   # 默认8090. 无需修改. jFrog提供的docker registry port
  BK_CI_DOCKER_REGISTRY_PASSWORD:   # 无默认值. 按需修改.
  BK_CI_DOCKER_REGISTRY_URL:   # 无默认值. 按需修改. docker regirsty入口, 需要协议前缀.
  BK_CI_DOCKER_REGISTRY_USER:   # 无默认值. 按需修改. 如果填写, 则启用认证.
  BK_CI_DOCKER_URL:   # 无默认值. 按需修改. Docker的web入口, 需要协议前缀.
  BK_CI_ES_CLUSTER_NAME: bkee-es   # 默认bkee-es. 按需修改. ES集群名称. 默认使用蓝鲸自动部署的ES名称.
  BK_CI_ES_REST_ADDR: es-ci.service.consul   # 默认es-ci.service.consul. 按需修改. ElasticSearch REST入口. HOST:PORT
  BK_CI_ES_REST_PORT: 9200   # 默认9200. 按需修改. ElasticSearch REST API端口
  BK_CI_INFLUXDB_ADDR: influxdb-ci.service.consul:8086   # 默认influxdb-ci.service.consul:8086. 按需修改. 第三方构建机状态上报时用. BK_CI_ENVIRONMENT_AGENT_COLLECTOR_ON
  BK_CI_INFLUXDB_DB: agentMetrix   # 默认agentMetrix. 请勿修改. 采集数据的数据库名.
  BK_CI_INFLUXDB_HOST: influxdb-ci.service.consul   # 默认influxdb-ci.service.consul. 按需修改. 网关目前需要分别指定主机名及端口
  BK_CI_INFLUXDB_PASSWORD:   # 无默认值. 按需修改.
  BK_CI_INFLUXDB_PORT: 8086   # 默认8086. 按需修改.
  BK_CI_INFLUXDB_USER: bk_ci   # 默认bk_ci. 按需修改.
  BK_CI_JFROG_FQDN:   # 无默认值. 按需修改. jFrog完全合格域名
  BK_CI_JFROG_HTTP_PORT: 8080   # 默认8080. 按需修改. jFrog构件下载服务的http端口
  BK_CI_JFROG_PASSWORD:   # 无默认值. 按需修改.
  BK_CI_JFROG_URL:   # 无默认值. 按需修改.
  BK_CI_JFROG_USER: bk_ci   # 默认bk_ci. 按需修改.
  BK_CI_S3_ACCESS_KEY:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_S3_BUCKET_NAME:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_S3_ENDPOINT_URL:   # 无默认值. 废弃. 待清理配置文件及相关代码.
  BK_CI_S3_SECRET_KEY:   # 无默认值. 废弃. 待清理配置文件及相关代码.

  ##########
  #codecc common
  ##########
  BK_CODECC_RABBITMQ_ADDR: rabbitmq.bkci:5672 # 默认rabbitmq-codecc.service.consul:5672. 按需修改. CODECC专用的RabbitMQ地址, HOST:PORT形式.
  BK_CODECC_RABBITMQ_PASSWORD:  # 无默认值. 按需修改.
  BK_CODECC_RABBITMQ_USER: bkcodecc # 默认codecc. 按需修改.
  BK_CODECC_RABBITMQ_VHOST: bkcodecc # 默认codecc. 按需修改. 建议使用独立的vhost.

  BK_CODECC_REDIS_HOST: 127.0.0.1 # 默认redis-codecc.service.consul. 按需修改. CODECC专用的Redis地址.
  BK_CODECC_REDIS_PASSWORD:  # 无默认值. 按需修改.
  BK_CODECC_REDIS_PORT: 6379 # 默认6379. 按需修改.
  BK_CODECC_REDIS_DB: 1 # 默认值为1. 按需修改. 选择使用的db.

  BK_CODECC_MONGODB_HOST: 127.0.0.1 # 默认mongodb-ci.service.consul. 按需修改. CODECC专用的Mongodb数据库地址.
  BK_CODECC_MONGODB_USER: bkcodecc # 默认bk_codecc. 按需修改.
  BK_CODECC_MONGODB_PASSWORD:  # 无默认值. 按需修改.
  BK_CODECC_MONGODB_PORT: 27017 # 默认27017. 按需修改.

  BK_CODECC_CONSUL_DISCOVERY_TAG: codecc # 默认codecc. 无需修改. 服务发现时的标签, 兼作服务名命名空间(后缀).
  BK_CODECC_CONSUL_HTTP_PORT: 8500 # 默认8500. consul服务发现的端口

  BK_CODECC_FQDN:    # 默认codecc.bk.tencent.com. 按需修改. 完全合格域名(即公网域名, 可解析为内网IP), 用于在CODECC集群外访问CODECC.

  BK_CI_PUBLIC_HOST:

  ##########
  #codecc service
  ##########
  BK_CODECC_APIQUERY_API_PORT: 38081 # 默认38081. 无需修改.
  BK_CODECC_ASYNCREPORT_API_PORT: 38091 # 默认38091. 无需修改.
  BK_CODECC_CODECCJOB_API_PORT: 38084 # 默认38084. 无需修改.
  BK_CODECC_DEFECT_API_PORT: 38082 # 默认38082. 无需修改.
  BK_CODECC_QUARTZ_API_PORT: 38089 # 默认38089. 无需修改.
  BK_CODECC_REPORT_API_PORT: 38083 # 默认38083. 无需修改.
  BK_CODECC_TASK_API_PORT: 38087 # 默认38087. 无需修改.
  BK_CODECC_OPENAPI_API_PORT: 38079 # 默认38079. 无需修改.
  BK_CODECC_SCHEDULE_API_PORT: 38086 # 默认38086. 无需修改.

  BK_CODECC_DISPATCH_IMAGE_NAME: linux # 默认linux, codecc独立入口任务用到的镜像
  BK_CODECC_DISPATCH_IMAGE_VERSION: 1.* # 默认1.*, codecc独立入口任务用到的镜像版本
  BK_CODECC_ENCRYPTOR_KEY: abcde # 默认abcde, codecc加密存储用到的key

  BK_CODECC_TASK_ANALYSIS_MAX_HOUR: 7 # 默认7, 任务分析的最大时间, 单位小时
