apiVersion: v2
name: bk-codecc
description: A Helm chart for CodeCC
type: application
version: __chart_backend_tag__
appVersion: __image_backend_tag__
home: "https://github.com/Tencent/bk-ci"

dependencies:
- name: common
  version: 2.19.1
  repository: https://charts.bitnami.com/bitnami
- name: nginx-ingress-controller
  version: 7.4.8
  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
  condition: nginx-ingress-controller.enabled
- name: mongodb
  version: 10.30.6
  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
  condition: mongodb.enabled
- name: rabbitmq
  version: 10.3.9
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
- name: redis
  version: 16.13.2
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
