# 服务配置文件模板
spring:
  application:
    name: asyncreport${service.suffix.codecc}
    desc: AsyncReport Service
    packageName: com.tencent.bk.codecc.defect
  data:
    mongodb:
      uri: mongodb://__BK_CODECC_MONGODB_USER__:__BK_CODECC_MONGODB_PASSWORD__@__BK_CODECC_MONGODB_ADDR__/db_defect?readPreference=secondaryPreferred

server:
  port: __BK_CODECC_ASYNCREPORT_API_PORT__ # 服务端口

