# 服务配置文件模板
spring:
  application:
    name: schedule${service.suffix.codecc}
    desc: Schedule Service
    packageName: com.tencent.bk.codecc.schedule
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    mongodb:
      uri: mongodb://__BK_CODECC_MONGODB_USER__:__BK_CODECC_MONGODB_PASSWORD__@__BK_CODECC_MONGODB_ADDR__/db_schedule?readPreference=secondaryPreferred

server:
  port: __BK_CODECC_SCHEDULE_API_PORT__ # 服务端口

codecc:
  file:
    data:
      path: __BK_CODECC_FILE_DATA_PATH__