# 服务配置文件模板
spring:
  application:
    name: codeccjob
    desc: CodeCCJob Service
    packageName: com.tencent.bk.codecc.codeccjob
  data:
    mongodb:
      uri: mongodb://__BK_CODECC_MONGODB_USER__:__BK_CODECC_MONGODB_PASSWORD__@__BK_CODECC_MONGODB_ADDR__/db_defect?readPreference=secondaryPreferred
  rabbitmq:
    devops:
      virtual-host: __BK_CODECC_RABBITMQ_VHOST__
      username: __BK_CODECC_RABBITMQ_USER__
      password: __BK_CODECC_RABBITMQ_PASSWORD__
      addresses: __BK_CODECC_RABBITMQ_ADDR__

server:
  port: __BK_CODECC_CODECCJOB_API_PORT__
