spring:
  application:
    name: apiquery${service.suffix.codecc}
    desc: Apiquery Service
    packageName: com.tencent.bk.codecc.apiquery
  data:
    mongodb:
      taskdb:
        uri: mongodb://__BK_CODECC_MONGODB_USER__:__BK_CODECC_MONGODB_PASSWORD__@__BK_CODECC_MONGODB_ADDR__/db_task?readPreference=secondaryPreferred
      defectdb:
        uri: mongodb://__BK_CODECC_MONGODB_USER__:__BK_CODECC_MONGODB_PASSWORD__@__BK_CODECC_MONGODB_ADDR__/db_defect?readPreference=secondaryPreferred
      opdb:
        uri: mongodb://__BK_CODECC_MONGODB_USER__:__BK_CODECC_MONGODB_PASSWORD__@__BK_CODECC_MONGODB_ADDR__/db_op?readPreference=secondaryPreferred

server:
  port: __BK_CODECC_APIQUERY_API_PORT__ # 服务端口


time:
  analysis:
    maxhour: __BK_CODECC_TASK_ANALYSIS_MAX_HOUR__

