# 服务配置文件模板
spring:
  application:
    name: codeccjob${service.suffix.codecc}
    desc: CodeCCJob Service
    packageName: com.tencent.bk.codecc.codeccjob
  data:
    mongodb:
      uri: mongodb://__BK_CODECC_MONGODB_USER__:__BK_CODECC_MONGODB_PASSWORD__@__BK_CODECC_MONGODB_ADDR__/db_defect?readPreference=secondaryPreferred

server:
  port: __BK_CODECC_CODECCJOB_API_PORT__
