{{- if .Values.codeccjob.enabled -}}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}-codeccjob
  labels: {{- include "codecc.labels.standard" . | nindent 4 }}
    app.kubernetes.io/name: codeccjob
    app.kubernetes.io/component: microservice
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "common.names.fullname" . }}-codeccjob
  selector:
    matchLabels: {{- include "codecc.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/name: codeccjob
      app.kubernetes.io/component: microservice
  replicas: {{ default 1 .Values.codeccjob.replicaCount }}
  template:
    metadata:
      labels: {{- include "codecc.labels.standard" . | nindent 8 }}
        app.kubernetes.io/name: codeccjob
        app.kubernetes.io/component: microservice
        {{- if .Values.codeccjob.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.codeccjob.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "codecc.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.codeccjob.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.codeccjob.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.codeccjob.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.codeccjob.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.codeccjob.podAffinityPreset "component" "codeccjob" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.codeccjob.podAntiAffinityPreset "component" "codeccjob" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.codeccjob.nodeAffinityPreset.type "key" .Values.codeccjob.nodeAffinityPreset.key "values" .Values.codeccjob.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.codeccjob.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.codeccjob.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.codeccjob.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.codeccjob.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.codeccjob.priorityClassName }}
      priorityClassName: {{ .Values.codeccjob.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.codeccjob.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.codeccjob.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: codeccjob
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.codeccjob.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.codeccjob.image.pullPolicy }}
          {{- if .Values.codeccjob.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.codeccjob.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.codeccjob.resources }}
          resources: {{- toYaml .Values.codeccjob.resources | nindent 12 }}
          {{- end }}
          env:
            - name: MS_NAME
              value: codeccjob
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: JVM_XMS
              value: {{ .Values.codeccjob.env.JVM_XMS }}
            - name: JVM_XMX
              value: {{ .Values.codeccjob.env.JVM_XMX }}
            - name: JVM_OPTIONS
              value: {{ .Values.codeccjob.env.JVM_OPTIONS }}
            - name: SERVICE_PREFIX
              value: {{ include "common.names.fullname" . }}-
            - name: SERVICE_SUFFIX
              value: {{ .Values.config.bkCodeccServiceSuffix }}
            - name: CODECC_PROFILE
              value: {{ .Values.common.springProfile }}
            - name: SERVER_STORAGE_MOUNT_PATH
              value: {{ .Values.config.bkCodeccFileDataPath }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: http
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.common.mountPath }}
            {{- if eq .Values.config.bkCodeccStorageType "local" }}
            - name: local-data
              mountPath: {{ .Values.config.bkCodeccFileDataPath }}
            {{- end }}
            {{- if eq .Values.config.bkCodeccStorageType "nfs" }}
            - name: nfs-data
              mountPath: {{ .Values.config.bkCodeccFileDataPath }}
            {{- end }}
            {{- if eq .Values.config.bkCodeccStorageType "bkrepo-csi" }}
            - name: bkrepo-csi-data
              mountPath: {{ .Values.config.bkCodeccFileDataPath }}
            {{- end }}
      volumes:
        - name: storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "common.names.fullname" . }}-storage{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if eq .Values.config.bkCodeccStorageType "local" }}
        - name: local-data
          hostPath:
            path: {{ .Values.config.bkCodeccLocalPath }}
        {{- end }}
        {{- if eq .Values.config.bkCodeccStorageType "nfs" }}
        - name: nfs-data
          nfs:
            server: {{ .Values.config.bkCodeccNfsServer }}
            path: {{ .Values.config.bkCodeccNfsServerPath }}
        {{- end }}
        {{- if eq .Values.config.bkCodeccStorageType "bkrepo-csi" }}
        - name: bkrepo-csi-data
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}-csi-bkrepo-pvc
        {{- end }}
{{- end }}
