object Release {
    const val Group = "com.tencent.devops"
    const val Version = "0.0.1"
}

object Versions {
    const val Kotlin = "1.6.0"
    const val swaggerVersion = "1.6.2"
    const val jaxrsVersion = "2.0"
    const val hashidsVersion = "1.0.3"
    const val feignVersion = "10.10.1"
    const val svnkitVersion = "1.9.3"
    const val vmwareVersion = "5.1"
    const val okHttpVersion = "4.9.0"
    const val commonExecVersion = "1.3"
    const val bouncyCastleVersion = "1.46"
    const val dom4jVersion = "1.6.1"
    const val slf4jVersion = "1.7.30"
    const val mockitoVersion = "1.10.19"
    const val httpclientVersion = "4.5.13"
    const val compressVersion = "1.15"
    const val jjwtVersion = "0.9.0"
    const val jsonLibVersion = "2.4"
    const val commonLang3Version = "3.5"
    const val guavaVersion = "30.0-jre"
    const val cronutilsVersion = "9.1.6"
    const val reflectionsVersion = "0.9.11"
    const val jsonSchemaVersion = "2.2.6"
    const val logbackVersion = "1.1.11"
    const val jasyptVersion = "2.0.0"
    const val jolokiaVersion = "1.6.2"
    const val awsS3Version = "1.11.461"
    const val poiVersion = "4.1.1"
    const val springWebSocketVersion = "2.3.4.RELEASE"
    const val lombokVersion = "1.18.16"
    const val tomcatEmbedCoreVersion = "9.0.39"
    const val commonCollection = "3.2.2"
//    const val commonPool2Version = "2.9.0"
    const val lettuceVersion = "4.5.0.Final"
    const val jerseyValidationVersion = "2.34"
    const val commonsIOVersion = "2.8.0"
    const val xmlrpcVersion = "3.1.3"
    const val commonsHttpclientVersion = "3.1"
    const val jsonVersion = "20180130"
    const val redissionVersion = "3.17.3"
    const val log4jVersion = "2.17.1"
    const val easyexcel = "2.2.7"
    const val redisson = "3.15.4"
    const val ktlintVersion = "0.29.0"
    const val lucene = "8.11.0"
    const val fastjson = "1.2.83"
    const val quartz = "2.1.3"
    const val quartzJobs = "2.2.3"
    const val micrometerVersion = "1.6.6"
    const val opentelemetryVersion = "1.17.0"
    const val iamSdkVersion = "1.0.21-SNAPSHOT"
    const val reflectasmVersion = "1.11.9"
    const val cryptSdkVersion = "1.1.3"

    // Devops 依赖版本
    const val devopsVersion = "1.13.0"
    const val commonText = "1.10.0"
    const val emojiJava = "5.1.1"
    const val commonCsv = "1.8"
    const val p4 = "2021.1.2163843"
    const val pinyinPlus = "1.0"
    const val jgit = "5.13.1.202206130422-r"
    const val bkRepoVersion = "1.0.1"
    const val ant = "1.10.5"
    const val kotlinxVersion = "1.6.0"
    const val cosVersion = "5.6.185"
    const val xzVersion = "1.9"

}
